# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: tokfile 0.0.4 ruby lib

Gem::Specification.new do |s|
  s.name = "tokfile"
  s.version = "0.0.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Edmund Highcock"]
  s.date = "2015-08-09"
  s.description = "A tool for working with common tokamak file formats from tools like EFIT, CHEASE, TRANSP, CRONOS etc. Contains commands for plotting a summary of content, manipulating the data within them and most importantly, converting one format to another."
  s.email = "edmundhighcock@users.sourceforge.net"
  s.executables = ["tokfile"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "LICENSE.txt",
    "README.md",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/tokfile",
    "lib/tokfile.rb",
    "lib/tokfile/commands.rb",
    "lib/tokfile/eqdsk.rb",
    "lib/tokfile/ogyropsi.rb",
    "test/data/EQDSK",
    "test/data/ogyropsi.dat",
    "test/data/ogyropsi_nobal.dat",
    "test/data/ogyropsi_out.dat",
    "test/helper.rb",
    "test/test_tokfile.rb",
    "tokfile.gemspec"
  ]
  s.homepage = "http://github.com/edmundhighcock/tokfile"
  s.licenses = ["GPLv3"]
  s.rubygems_version = "2.4.8"
  s.summary = "A set of tools for testing and manipulating and converting files associated with tokamaks."

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<coderunner>, [">= 0.14.13"])
      s.add_runtime_dependency(%q<graphkit>, [">= 0.3.3"])
      s.add_runtime_dependency(%q<command-line-flunky>, [">= 1.0.0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
    else
      s.add_dependency(%q<coderunner>, [">= 0.14.13"])
      s.add_dependency(%q<graphkit>, [">= 0.3.3"])
      s.add_dependency(%q<command-line-flunky>, [">= 1.0.0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_dependency(%q<simplecov>, [">= 0"])
    end
  else
    s.add_dependency(%q<coderunner>, [">= 0.14.13"])
    s.add_dependency(%q<graphkit>, [">= 0.3.3"])
    s.add_dependency(%q<command-line-flunky>, [">= 1.0.0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    s.add_dependency(%q<simplecov>, [">= 0"])
  end
end

