# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: tokfile 0.0.9 ruby lib

Gem::Specification.new do |s|
  s.name = "tokfile".freeze
  s.version = "0.0.9"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Edmund Highcock".freeze]
  s.date = "2017-01-26"
  s.description = "A tool for working with common tokamak file formats from tools like EFIT, CHEASE, TRANSP, CRONOS etc. Contains commands for plotting a summary of content, manipulating the data within them and most importantly, converting one format to another.".freeze
  s.email = "edmundhighcock@users.sourceforge.net".freeze
  s.executables = ["tokfile".freeze]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "LICENSE.txt",
    "README.md",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/tokfile",
    "lib/tokfile.rb",
    "lib/tokfile/commands.rb",
    "lib/tokfile/eqdsk.rb",
    "lib/tokfile/ogyropsi.rb",
    "test/data/EQDSK",
    "test/data/EQDSK_NO_BOUNDARY",
    "test/data/ogyropsi.dat",
    "test/data/ogyropsi_nobal.dat",
    "test/data/ogyropsi_out.dat",
    "test/helper.rb",
    "test/test_tokfile.rb",
    "tokfile.gemspec"
  ]
  s.homepage = "http://github.com/edmundhighcock/tokfile".freeze
  s.licenses = ["GPLv3".freeze]
  s.rubygems_version = "2.6.8".freeze
  s.summary = "A set of tools for testing and manipulating and converting files associated with tokamaks.".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<coderunner>.freeze, [">= 0.14.13"])
      s.add_runtime_dependency(%q<graphkit>.freeze, [">= 0.3.3"])
      s.add_runtime_dependency(%q<command-line-flunky>.freeze, [">= 1.0.0"])
      s.add_development_dependency(%q<shoulda>.freeze, [">= 0"])
      s.add_development_dependency(%q<rdoc>.freeze, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>.freeze, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>.freeze, ["~> 2.3.2"])
      s.add_development_dependency(%q<simplecov>.freeze, [">= 0"])
    else
      s.add_dependency(%q<coderunner>.freeze, [">= 0.14.13"])
      s.add_dependency(%q<graphkit>.freeze, [">= 0.3.3"])
      s.add_dependency(%q<command-line-flunky>.freeze, [">= 1.0.0"])
      s.add_dependency(%q<shoulda>.freeze, [">= 0"])
      s.add_dependency(%q<rdoc>.freeze, ["~> 3.12"])
      s.add_dependency(%q<bundler>.freeze, ["~> 1.0"])
      s.add_dependency(%q<jeweler>.freeze, ["~> 2.3.2"])
      s.add_dependency(%q<simplecov>.freeze, [">= 0"])
    end
  else
    s.add_dependency(%q<coderunner>.freeze, [">= 0.14.13"])
    s.add_dependency(%q<graphkit>.freeze, [">= 0.3.3"])
    s.add_dependency(%q<command-line-flunky>.freeze, [">= 1.0.0"])
    s.add_dependency(%q<shoulda>.freeze, [">= 0"])
    s.add_dependency(%q<rdoc>.freeze, ["~> 3.12"])
    s.add_dependency(%q<bundler>.freeze, ["~> 1.0"])
    s.add_dependency(%q<jeweler>.freeze, ["~> 2.3.2"])
    s.add_dependency(%q<simplecov>.freeze, [">= 0"])
  end
end

